// Generated by Rec Studio 4 - build Jul 23 2013

_init()
{// addr = 0x00400928
    call_gmon_start();
    frame_dummy(__rax);
    __do_global_ctors_aux();
    return;
}

char* getenv(char* __name)
{// addr = 0x00400950
    goto __imp__getenv;
}

void free(void* __ptr)
{// addr = 0x00400960
    goto __imp__free;
}

int strncmp(char* __s1, char* __s2, int __n)
{// addr = 0x00400970
    goto __imp__strncmp;
}

int fclose(struct _IO_FILE* fp)
{// addr = 0x00400980
    goto __imp__fclose;
}

getpwuid()
{// addr = 0x00400990
    goto __imp__getpwuid;
}

__stack_chk_fail()
{// addr = 0x004009A0
    goto __imp____stack_chk_fail;
}

short getuid()
{// addr = 0x004009B0
    goto __imp__getuid;
}

int getopt_long(int ___argc, __builtin_va_list* ___argv, char* __shortopts, struct option* __longopts, int* __longind)
{// addr = 0x004009C0
    goto __imp__getopt_long;
}

int fgetc(struct _IO_FILE* fp)
{// addr = 0x004009D0
    goto __imp__fgetc;
}

int fputc(int ch, struct _IO_FILE* fp)
{// addr = 0x004009E0
    goto __imp__fputc;
}

__libc_start_main()
{// addr = 0x004009F0
    goto __imp____libc_start_main;
}

int fprintf(struct _IO_FILE* fp, char* format)
{// addr = 0x00400A00
    goto __imp__fprintf;
}

umask()
{// addr = 0x00400A10
    goto __imp__umask;
}

__xpg_basename()
{// addr = 0x00400A20
    goto __imp____xpg_basename;
}

int access(char* __name, int __type)
{// addr = 0x00400A30
    goto __imp__access;
}

struct _IO_FILE* fopen(char* name, char* mode)
{// addr = 0x00400A40
    goto __imp__fopen;
}

void perror(char* msg)
{// addr = 0x00400A50
    goto __imp__perror;
}

char* strcat(char* __dest, char* __src)
{// addr = 0x00400A60
    goto __imp__strcat;
}

int sprintf(char* dst, char* format)
{// addr = 0x00400A70
    goto __imp__sprintf;
}

void exit(int __status)
{// addr = 0x00400A80
    goto __imp__exit;
}

int fwrite(void* src, int sz, int nitems, struct _IO_FILE* fp)
{// addr = 0x00400A90
    goto __imp__fwrite;
}

char* strdup(char* __s)
{// addr = 0x00400AA0
    goto __imp__strdup;
}

_start(
    _unknown_ __rax,                       // r53
    _unknown_ __rdx                        // r56
)
{// addr = 0x00400AB0
    long long* _t2;                        // _t2

    r9 = __rdx;
    _pop(__rsi);
    __rsp = __rsp & 240;
    _push(__rax);
    _push(__rsp);
    r8 = __libc_csu_fini;
    __libc_start_main();
    asm("hlt ");
    __rsp = __rsp - 8;
    _t2 = __imp____gmon_start__;
    if(_t2 != 0) {
         *_t2();
    }
    __rsp = __rsp + 8;
    return;
}

call_gmon_start()
{// addr = 0x00400ADC
    __rax = __imp____gmon_start__;
    if(__rax != 0) {
         *__rax();
        return;
    }
    return;
}

__do_global_dtors_aux()
{// addr = 0x00400B00
    _unknown_ __rbx;                       // r54
    _unknown_ __rbp;                       // r59
    signed long long _t6;                  // _t6
    signed long long _t7;                  // _t7
    _unknown_ _t8;                         // _t8
    _unknown_ _t11;                        // _t11

    if(completed.6531 == 0) {
        _t6 = dtor_idx.6533;
        _t11 = (_t8 -  &__DTOR_LIST__ >> 3) - 1;
        if(_t6 >= _t11) {
L4:
            completed.6531 = 1;
            return;
        }
        asm("o16 nop [eax+eax+0x0]");
        do {
            _t7 = _t6 + 1;
            dtor_idx.6533 = _t7;
             *((intOrPtr*)(_t7 * 8 +  &__DTOR_LIST__))();
            _t6 = dtor_idx.6533;
        } while(_t6 < _t11);
        goto L4;
    }
    return;
}

frame_dummy(
    _unknown_ __rax                        // r53
)
{// addr = 0x00400B70
    _unknown_ __rbp;                       // r59

    __rax = __rax;
    __rbp = __rsp;
    if(__JCR_LIST__ == 0) {
    } else {
        __eax = 0;
        if(__rax != 0) {
            _pop(__rbp);
            goto __rax;
        }
    }
    return __eax;
}

main(
    _unknown_ __eax                        // r0
)
{// addr = 0x00400B94
    int _v12;                              // _cfa_fffffff4
    intOrPtr _v16;                         // _cfa_fffffff0
    long long _v24;                        // _cfa_ffffffe8
    long long _v32;                        // _cfa_ffffffe0
    intOrPtr _v44;                         // _cfa_ffffffd4
    int _v56;                              // _cfa_ffffffc8
    int _t48;                              // _t48
    intOrPtr _t53;                         // _t53
    long long _t75;                        // _t75
    struct option* _t79;   // _t79
    char* _t82;                            // _t82
    int _t89;                              // _t89
    int _t93;                              // _t93
    int _t94;                              // _t94

    _v44 = _t53;
    _v56 = _t93;
    _v16 = 0;
    _v24 =  &optstr;
    _v32 =  &opts;
    goto L2;
    do {
    } while();
    goto L5;
L2:
    if( *_v32 != 0) {
         *_v24 =  *((intOrPtr*)(_v32 + 24));
        _v24 = _v24 + 1;
        _v32 = _v32 + 32;
        goto L2;
    } else {
        _t75 = _v24;
         *_t75 = 0;
        getenv(_t89);
        _v24 = _t75;
        if(_v24 != 0) {
            _t75 = _v24;
            hwbase = _t75;
        }
    }
L5:
    getenv(_t89);
    _v24 = _t75;
    if(_v24 != 0) {
        hwsecret = _v24;
    }
    while(1) {
        _t94 = _v56;
        r8d = 0;
        _v12 = getopt_long(_t89, _t94, _t82, _t79, __r8);
        if(_v12 == 255) {
            break;
        }
        _t48 = _v12;
        if(_t48 == 104) {
L18:
            usage(0, __rbx, _t94);
            continue;
        }
        if(_t48 > 104) {
            if(_t48 == 118) {
                verbose = 1;
            }
L19:
            continue;
        }
        if(_t48 == 63) {
            usage(1, __rbx, _t94);
            goto L18;
        }
        if(_t48 == 100) {
            debug = 1;
        }
        goto L19;
    }
    if(__imp__optind == _v44) {
        fwrite(__imp__stderr, _t94, __imp__stderr, _t77);
        usage(2, __rbx, _t94);
    }
    if(debug != 0) {
        fwrite(__imp__stderr, _t94, __imp__stderr, _t76);
    }
    umask();
    while(__imp__optind < _v44) {
        __imp__optind = __imp__optind + 1;
        if(addfile(__imp__optind + 1) != 0) {
            _v16 = 1;
        }
    }
    return _v16;
}

addfile(
    _unknown_ __eax                        // r0
)
{// addr = 0x00400D53
    long long _v16;                        // _cfa_fffffff0
    char _v280;                            // _cfa_fffffee8
    char _v281;                            // _cfa_fffffee7
    intOrPtr _v288;                        // _cfa_fffffee0
    struct _IO_FILE* _v296;   // _cfa_fffffed8
    char* _v304;                           // _cfa_fffffed0
    struct _IO_FILE* _v312;   // _cfa_fffffec8
    void* _v320;          // _cfa_fffffec0
    char* _v328;                           // _cfa_fffffeb8
    _unknown_ __rbp;                       // r59
    char* _t62;                            // _t62
    _unknown_ _t83;                        // _t83
    char* _t92;                            // _t92
    char* _t93;                            // _t93
    char* _t97;                            // _t97
    struct _IO_FILE* _t105;   // _t105
    int _t106;                             // _t106
    int _t107;                             // _t107
    char* _t108;                           // _t108
    char* _t112;                           // _t112
    char* _t113;                           // _t113
    char* _t118;                           // _t118
    int _t137;                             // _t137

    _v320 = _t118;
    _v16 =  *fs:0x28];
    _v288 = 0;
    if(verbose != 0) {
        if(debug == 0) {
            _t105 = __imp__stdout;
        } else {
            _t105 = __imp__stderr;
        }
        _t137 = _t106;
        fprintf(_t105, _t137);
    }
    _t83 = checkname(_t106, _v320);
    if(_t83 == 0) {
        _t107 = hwsecret;
        sprintf( &_v280, _t137);
        if(debug != 0) {
            _t137 = _t107;
            fprintf(__imp__stderr, _t137);
        }
        if(access( &_v280, _t137) == 0) {
            _v328 = 4294967295;
            _t108 = _v328;
            asm("repne scasb ");
            _t112 =  !_t108 - 1 +  &_v280;
             *_t112 =  *_t137 & 65535;
            if(debug != 0) {
                _t112 =  &_v280;
                fprintf(__imp__stderr, _t108);
            }
            _t92 = _v320;
            fopen(_t92, _t112);
            _v312 = _t92;
            if(_v312 != 0) {
                _t93 = _v320;
                strdup(_t93);
                _v320 = _t93;
                __xpg_basename();
                _v304 = _v320;
                _t113 = _v304;
                strcat( &_v280, _t113);
                free(_v320);
                if(debug != 0) {
                    _t113 =  &_v280;
                    fprintf(__imp__stderr, _t108);
                }
                _t97 =  &_v280;
                fopen(_t97, _t113);
                _v296 = _t97;
                if(_v296 != 0) {
                    while(1) {
                        __rax = _v312;
                        __rdi = _v312;
                        fgetc(__rdi);
                        _v281 = __al;
                        if(_v281 == 255) {
                            break;
                        }
                        fputc(__rdi, _v296);
                        _v288 = _v288 + 1;
                    }
                    __rax = _v312;
                    __rdi = _v312;
                    fclose(_v312);
                    __rax = _v296;
                    __rdi = _v296;
                    fclose(_v296);
                    if(debug != 0) {
                        __rax = __imp__stderr;
                        __rdi = __imp__stderr;
                        fprintf(__imp__stderr, __rcx);
                    }
                    if(verbose != 0) {
                        if(debug == 0) {
                            __rax = __imp__stdout;
                        } else {
                            __rax = __imp__stderr;
                        }
                        __rdi = __rax;
                        fprintf(__rax, __rcx);
                    }
                } else {
                    perror( &_v280);
                    fclose(_v312);
                    _t62 = 4294967295;
                }
            } else {
                perror(_v320);
                _t62 = 4294967295;
            }
        } else {
            perror( &_v280);
            _t62 = 4294967295;
        }
    } else {
        _t62 = 4294967295;
    }
    if(_t83 != 0) {
        __stack_chk_fail();
        return _t62;
    }
    return _t62;
}

checkname(
    char* __rcx,                           // r55
    void* __rdi           // r57
)
{// addr = 0x004010C9
    short _v12;                            // _cfa_fffffff4
    int _v16;                              // _cfa_fffffff0
    char* _v24;                            // _cfa_ffffffe8
    struct _IO_FILE* _v32;   // _cfa_ffffffe0
    char* _v48;                            // _cfa_ffffffd0
    char* _v56;                            // _cfa_ffffffc8
    _unknown_ __rbp;                       // r59
    intOrPtr _t91;                         // _t91
    struct _IO_FILE* _t98;   // _t98
    char* _t104;                           // _t104
    char* _t107;                           // _t107
    char* _t120;                           // _t120
    int _t151;                             // _t151
    int _t153;                             // _t153

    _v48 = __rdi;
    if(debug != 0) {
        _t151 = __rcx;
        fprintf(__imp__stderr, __rcx);
    }
    _t91 = debug;
    if(_t91 != 0) {
        fwrite(__imp__stderr, _t151, __imp__stderr, _t117);
    }
    _v56 = 4294967295;
    _t120 = _v56;
    asm("repne scasb ");
    _v16 = 0;
    _t98 =  !_t120 - 0xfffffffffffffffd + _v48;
    asm("rep cmpsb ");
    if(_t91 > 0 == _t91 > 0) {
        _v12 = getuid();
        if(debug != 0) {
            _t98 = __imp__stderr;
            fprintf(_t98, _t120);
        }
        getpwuid();
        _v32 = _t98;
        if(_v32 != 0) {
            if(debug != 0) {
                fprintf(__imp__stderr, _t120);
            }
            _v56 = 4294967295;
            asm("repne scasb ");
            _v16 = 0;
            _t104 = _v48;
            strdup(_t104);
            _v48 = _t104;
            __xpg_basename();
            _v24 = _v48;
            _t107 = _v24;
            _t153 =  *_v32;
            if(strncmp(_t107, _t153, _v16) != 0 || ((_t107[_v24]) & 255) != 45) {
                fprintf(__imp__stderr, _t153);
                return 4294967295;
            } else {
                free(_v48);
                if(debug != 0) {
                    fwrite(__imp__stderr, _t153, __imp__stderr, _t112);
                }
                return 0;
            }
        } else {
            fprintf(__imp__stderr, _t120);
            return 4294967295;
        }
    } else {
        fprintf(__imp__stderr, _t120);
        return 4294967295;
    }
}

usage(
    intOrPtr __edi,                        // r4
    long long __rbx,                       // r54
    int __rsi                              // r58
)
{// addr = 0x00401338
    long long _v16;                        // _cfa_fffffff0
    intOrPtr _v28;                         // _cfa_ffffffe4
    int _v48;                              // _cfa_ffffffd0
    int _v56;                              // _cfa_ffffffc8
    intOrPtr _v64;                         // _cfa_ffffffc0
    intOrPtr _v72;                         // _cfa_ffffffb8
    long long _v80;                        // _cfa_ffffffb0
    long long _v88;                        // _cfa_ffffffa8
    intOrPtr _t36;                         // _t36
    int _t52;                              // _t52
    long long _t53;                        // _t53
    int _t61;                              // _t61
    int _t66;                              // _t66
    int _t67;                              // _t67
    _unknown_ _t69;                        // _t69
    long long _t70;                        // _t70
    signed long long _t73;                 // _t73

    _t67 = __rsi;
    _t53 = __rbx;
    _push(_t69);
    _t70 = __rsp;
    __rsp = __rsp - 32;
    _v28 = __edi;
    fwrite(__imp__stderr, __rsi, __imp__stderr, _t45);
    _v16 = 6299904;
    while( *_v16 != 0) {
        fprintf(__imp__stderr, _t67);
        _v16 = _v16 + 32;
    }
    fwrite(__imp__stderr, _t67, __imp__stderr, _t51);
    _t52 = __imp__stderr;
    _t61 = _t52;
    _t66 = _t52;
    fwrite(_t66, _t67, _t61, _t61);
    _t36 = _v28;
    exit(_t66);
    _v80 = _t70;
    _v72 = r12;
    r12 = 6299172;
    _v64 = r13;
    _v56 = r14;
    _v48 = r15;
    _v88 = _t53;
    __rsp = __rsp - 56;
    r13d = _t36;
    r14 = _t67;
    _t73 = 6299172 - r12 >> 3;
    r15 = _t61;
    _init();
    if(6299172 == 0) {
    } else {
        do {
             *r12+rbx*8]();
            _t53 = _t53 + 1;
        } while(_t53 != _t73);
    }
    r12 = _v72;
    r13 = _v64;
    r14 = _v56;
    r15 = _v48;
    __rsp = __rsp + 56;
    return;
}

__libc_csu_init(
    _unknown_ __edi,                       // r4
    long long __rbx,                       // r54
    intOrPtr __rdx,                        // r56
    intOrPtr __rsi,                        // r58
    long long __rbp                        // r59
)
{// addr = 0x00401400
    intOrPtr _v8;                          // _cfa_fffffff8
    intOrPtr _v16;                         // _cfa_fffffff0
    intOrPtr _v24;                         // _cfa_ffffffe8
    intOrPtr _v32;                         // _cfa_ffffffe0
    long long _v40;                        // _cfa_ffffffd8
    long long _v48;                        // _cfa_ffffffd0
    long long _t17;                        // _t17
    signed long long _t26;                 // _t26

    _t17 = __rbx;
    _v40 = __rbp;
    _v32 = r12;
    r12 = 6299172;
    _v24 = r13;
    _v16 = r14;
    _v8 = r15;
    _v48 = __rbx;
    __rsp = __rsp - 56;
    r13d = __edi;
    r14 = __rsi;
    _t26 = 6299172 - r12 >> 3;
    r15 = __rdx;
    _init();
    if(6299172 == 0) {
    } else {
        do {
             *r12+rbx*8]();
            _t17 = _t17 + 1;
        } while(_t17 != _t26);
    }
    r12 = _v32;
    r13 = _v24;
    r14 = _v16;
    r15 = _v8;
    __rsp = __rsp + 56;
    return;
}

__libc_csu_fini()
{// addr = 0x00401490
    intOrPtr* __rbx;                       // r54
    _unknown_ __rbp;                       // r59
    _unknown_ _t3;                         // _t3

    asm("rep ret ");
    0;
    0;
    _push(_t3);
    _push(__rbx);
    __rsp = __rsp - 8;
    __rax = __CTOR_LIST__;
    if(__rax == 255) {
    } else {
        do {
            __rbx = __rbx - 8;
             *__rax();
            __rax =  *__rbx;
        } while(__rax != 255);
    }
    __rsp = __rsp + 8;
    _pop(__rbx);
    _pop(__rbp);
    return;
}

__do_global_ctors_aux()
{// addr = 0x004014A0
    intOrPtr* __rbx;                       // r54
    _unknown_ __rbp;                       // r59

    __rax = __CTOR_LIST__;
    if(__rax == 255) {
    } else {
        do {
            __rbx = __rbx - 8;
             *__rax();
            __rax =  *__rbx;
        } while(__rax != 255);
    }
    return;
}

_fini()
{// addr = 0x004014D8
    __do_global_dtors_aux();
    return;
}

_fini()
{// addr = 0x004014D8
    @rec __do_global_dtors_aux@__do_global_dtors_aux@();
    return;
}

// Statistics:
//      92 Register nodes
//     152 Temporaries nodes
//       2 Casts
//     409 Statements
//      10 Labels
//       6 Gotos
//      35 Blocks
//    1160 Nodes
//       7 Assembly nodes
//      18 Unknown Types


Total time: 0 seconds.
